### ISSUE TITLE
csv 文件 数据读取问题

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/R-Graphics#12]
<img width="304" alt="default" src="https://user-images.githubusercontent.com/12031874/30418722-8c053fc8-9966-11e7-8f3e-672f4329e262.PNG">

**Comment by Cloud2016** [comment]
<img width="444" alt="default" src="https://user-images.githubusercontent.com/12031874/30419200-1b936970-9968-11e7-8784-702967aa5342.PNG">
<img width="274" alt="2" src="https://user-images.githubusercontent.com/12031874/30419211-233f5ef4-9968-11e7-89f8-a4639384eeee.PNG">
