### ISSUE TITLE
cos barplot

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/R-Graphics#7]
![poisbar-1](https://user-images.githubusercontent.com/12031874/29483578-d90c9658-84db-11e7-85c9-d44db8994d33.png)
![airpassengers-1](https://user-images.githubusercontent.com/12031874/29483579-dda5eafc-84db-11e7-8728-0fb133189208.png)
![islr-1](https://user-images.githubusercontent.com/12031874/29483580-e1aef85a-84db-11e7-95ac-860d3c05879c.png)
![stacked bars-1](https://user-images.githubusercontent.com/12031874/29483581-e44f0cee-84db-11e7-9b72-52b12b66cd11.png)
![ucbadmissions-1](https://user-images.githubusercontent.com/12031874/29483585-e748622e-84db-11e7-938e-f08b90256813.png)
![dotplot-1](https://user-images.githubusercontent.com/12031874/29483586-eac14880-84db-11e7-80f3-5bfa593a34d3.png)

**Comment by Cloud2016** [comment]
![compositebar](https://user-images.githubusercontent.com/12031874/29483635-15bb4ac6-84dd-11e7-9c63-e36ef69a9eb5.png)

**Comment by Cloud2016** [comment]
用base plot重画点图
![dotplot](https://user-images.githubusercontent.com/12031874/29484779-6562d9d4-84f8-11e7-8955-4108a17d1984.png)

**Comment by Cloud2016** [comment]
国际航班乘客
![airpassengers-1](https://user-images.githubusercontent.com/12031874/29484850-10bf2d36-84fa-11e7-8343-3e7bb09209e8.png)

**Comment by Cloud2016** [comment]
复杂堆积条形图反例

![stackplot](https://user-images.githubusercontent.com/12031874/29492174-b5b739b8-85a5-11e7-80e7-a7466883b2b6.png)

应该使用马赛克图
![stackmosaicplot](https://user-images.githubusercontent.com/12031874/29492177-bb1e4b8a-85a5-11e7-9532-4e662b2786d8.png)

**Comment by Cloud2016** [comment]
![ucbadmissions-1](https://user-images.githubusercontent.com/12031874/29492181-e1131442-85a5-11e7-9d00-ca36f18d466f.png)
![ucbadmissions](https://user-images.githubusercontent.com/12031874/29492183-e4b3ca4c-85a5-11e7-9af1-858cb4c30eb9.png)
![ucbadmissions2](https://user-images.githubusercontent.com/12031874/29492195-2c1a2cfa-85a6-11e7-9c04-dbba83986442.png)

**Comment by Cloud2016** [comment]
![hist](https://user-images.githubusercontent.com/12031874/29704567-f2af53fe-89ac-11e7-896a-53232349181a.png)

**Comment by Cloud2016** [comment]
![dotplot](https://user-images.githubusercontent.com/12031874/29740032-fe177914-8a7f-11e7-850a-14619ad9411b.png)

**Comment by Cloud2016** [comment]
![dotplot](https://user-images.githubusercontent.com/12031874/29740087-1378d40a-8a81-11e7-949f-3be5956df129.png)

**Comment by Cloud2016** [comment]
![barplot](https://user-images.githubusercontent.com/12031874/29740193-954a5344-8a83-11e7-9108-f6ea78ccedbd.png)

**Comment by Cloud2016** [comment]
![bed_net](https://user-images.githubusercontent.com/12031874/29740264-234eedde-8a85-11e7-8425-5a60cda96845.png)

**Comment by Cloud2016** [comment]
![bar2](https://user-images.githubusercontent.com/12031874/29747239-77cf9c78-8b25-11e7-8c6c-11b80f8ed146.png)
![bar1](https://user-images.githubusercontent.com/12031874/29747240-7bb48e16-8b25-11e7-989d-f847501beda1.png)

**Comment by Cloud2016** [comment]
![untitled](https://user-images.githubusercontent.com/12031874/29818497-2c22c662-8cef-11e7-9c48-2b245d7d76f8.png)

**Comment by Cloud2016** [comment]
![untitled](https://user-images.githubusercontent.com/12031874/29819135-e7a3c4fc-8cf1-11e7-86c6-6aba140ff49f.png)

**Comment by Cloud2016** [comment]
![example](https://user-images.githubusercontent.com/12031874/29819490-9035f152-8cf3-11e7-83c1-414ade485b7e.png)

**Comment by Cloud2016** [comment]
立体三维柱形图
http://www.mckinsey.com/global-themes/urbanization/global-cities-of-the-future-an-interactive-map
